
# ---------------------------------- Program configuration ------------------------------------------------------------#
host: {"host": "localhost", "port": 9200}
json_forms_directory: "important_fields\\"
csv_forms_directory: "decease\\"
path_indossiers: "decease\\patients_selection_decease\\"
path_outdossiers: "decease\\patients_selection_decease_json\\"
# ---------------------------------------------------------------------------------------------------------------------#
read_dossiers: False
algo: "baseline" # "random" or "baseline"
data_path_root: "C:\\Users\\Christina Zavou\\Documents"  # ".." or "C:\Users\Christina Zavou\Documents"

assign_all: True
run_algo: True
forms: ["colorectaal"] #,"mamma"]

#fields_colorectaal: ['LOCPRIM','LOCPRIM2','SCOPDIST','SCOPDIST2','klachten_klacht1','klachten_klacht2',
#                     'klachten_klacht3','klachten_klacht4','klachten_klacht88','klachten_klacht99','SCORECT','SCORECT2',
#                     'RESTAG_SCORECT_1','RESTAG_SCORECT2_1','RESTAG_CT','SCORECN','SCORECN2','RESTAG_SCORECN_1',
#                     'RESTAG_SCORECN2_1','SCORECM','SCORECM2','RESTAG_SCORECM_1','RESTAG_SCORECM2_1','PROCOK','mdo_chir',
#                     'geenresectie_irres','geenresectie_meta','geenresectie_anders','geenresec_palltherYN','pall_NO_reden',
#                     'pallther_chemo','pallther_chemoSTUDIE','pallther_RT','pallther_RTstudie','pallther_chemoRT',
#                     'pallther_chemoRTstudie','pallther_startdatum','COMORB','COMORBCAR','COMORBVAS','COMORBDIA','COMORBPUL',
#                     'COMORBNEU','COMORBMDA','COMORBURO']

fields_colorectaal: ['LOCPRIM','LOCPRIM2','SCOPDIST','SCOPDIST2','klachten_klacht1','klachten_klacht2',
                     'klachten_klacht3','klachten_klacht4','klachten_klacht88','klachten_klacht99']

#fields_mamma: []

# if empty preprocess then take type_name_pp as is
preprocess: [] #['remove_codes','extrastop','remove_stopwords','add_synonyms','stem']
to_remove: ['newlin','newline', 'punctuation']
type_name_pp: "patient_1_1_1_0" # "patient_stem_stop_extrastop_synonyms" #"patient_stem_stop_extrastop_synonyms" or given name like patient_1_1_1_1 # always remove codes

unknowns: "include"
when_no_preference: "random" # "random" or "empty"
fuzziness: 2
with_description: False
# ---------------------------------------------------------------------------------------------------------------------#
index_name: "medical_info_extraction"
initmap_jfile: "mapping.json"
type_name_p: "patient"
type_name_f: "form"
type_name_s: "report_description_sentence"
