
dataset: expert\dataset_important_fields_expert.p  # should exists

n_grams_file: expert\config8\n_grams.json

forms: {
  'colorectaal': [  # without SCORECT !
  'klachten_klacht1', 'klachten_klacht2', 'klachten_klacht4',
  'LOCPRIM',
  'mdo_chir',
  'RESTAG_CT',
  'PROCOK'
  ]
}