

dataset: dataset_allfields_expert.p

json_form_file: "CONFIGURATIONS_PATH\\important_fields_expert\\tmp_important_fields_DECEASE.json"
csv_form_file: "DATA_PATH\\DECEASE\\selection_DECEASE.csv"
form_dossiers_path: "DATA_PATH\\DECEASE\\patients_selection_DECEASE"

mapping_file: "CONFIGURATIONS_PATH\\mapping_v2.json"

host: {"host": "localhost", "port": 9200}

es_index_name: dataset_allfields_expert

forms: {
  'colorectaal': []
}

use_description_1ofk: 1
patient_relevant: True # will become false if sklearn version is not 0.17.1
description_as_phrase: True
value_as_phrase: True
slop: 5
n_gram_field: "description.4_gram_description"
edit_distance: 3

